name: Deploy to AWS Lambda

on:
  push:
    branches:
      - main  # Change to your main branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: List Files for Debugging  # Add this step to list all files and directories
        run: ls -R  # Recursively list all directories and files

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.12'  # Match your Lambda runtime

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Install Serverless Framework
        run: npm install -g serverless

      - name: Authenticate with Serverless Framework
        run: serverless config credentials --provider aws --key ${{ secrets.AWS_ACCESS_KEY_ID }}  --secret ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      - name: Deploy to AWS
        env:
          SERVERLESS_ACCESS_KEY: ${{ secrets.SERVERLESS_ACCESS_KEY }}
        run: |
          cd snowscrape
          serverless deploy
