name: Deploy to AWS Lambda

on:
  push:
    branches:
      - main  # Trigger for production
      - dev   # Trigger for development

jobs:
  deploy:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        stage: [dev, prod]  # Define the two stages

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'  # Match your Lambda runtime

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Install Serverless Framework and Plugins
        run: |
          npm install -g serverless
          npm install --save-dev serverless-python-requirements

      - name: Deploy to AWS
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          SERVERLESS_ACCESS_KEY: ${{ secrets.SERVERLESS_ACCESS_KEY }}
        run: |
          if [ "${{ github.ref }}" == "refs/heads/main" ]; then
            serverless deploy --stage prod --debug
          elif [ "${{ github.ref }}" == "refs/heads/dev" ]; then
            serverless deploy --stage dev --debug
          fi
